{
  "codecov": {
    "notify": {},
    "require_ci_to_pass": true
  },
  "coverage": {
    "status": {
      "patch": {
        "default": {
          "target": 100
        }
      },
      "project": {
        "default": {
          "target": 100
        }
      }
    }
  }
}
