name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '8.2'
        dependencies:
          - lowest
          - highest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          ini-values: zend.assertions=1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --no-interaction --no-progress

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress

      - name: Run test suite
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Run demo (JSON)
        run: bin/asd docs/blog/profile.json && bin/asd docs/todomvc/profile.json && bin/asd --and-tag=a,b --or-tag=c --color=red docs/blog/profile.json

      - name: Run demo (XML)
        run: bin/asd docs/blog/profile.xml
