name: Release (app-state-diagram)
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: app-state-diagram
      VERSION_NAME: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build & Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: docker/app-state-diagram/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/alps-asd/app-state-diagram:latest
