name: Release (asd-action)
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: asd-action
      VERSION_NAME: latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:${{ env.VERSION_NAME }}
          file: docker/asd-action/Dockerfile
        env:
          DOCKER_BUILDKIT: 1
