name: Release (app-state-diagram)
on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: app-state-diagram
      VERSION_NAME: latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t alps-asd/app-state-diagram:latest --push .
