name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout homebrew repository
        uses: actions/checkout@v4
        with:
          repository: alps-asd/homebrew-asd
          ref: 1.x
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git user information
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get latest release tag
        id: latest_release
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            # For workflow_dispatch, get latest release from API
            TAG=$(curl -s https://api.github.com/repos/alps-asd/app-state-diagram/releases/latest | grep -o '"tag_name": "[^"]*' | cut -d'"' -f4)
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi

      - name: Download release phar
        run: |
          wget https://github.com/alps-asd/app-state-diagram/releases/download/${{ steps.latest_release.outputs.tag }}/asd.phar

      - name: Calculate SHA256
        id: sha
        run: |
          SHA=$(sha256sum asd.phar | awk '{ print $1 }')
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Update Ruby formula file
        run: |
          if [ -f "./asd.rb" ]; then 
            # Update URL
            sed -i "s|url \".*\"|url \"https://github.com/alps-asd/app-state-diagram/releases/download/${{ steps.latest_release.outputs.tag }}/asd.phar\"|" ./asd.rb
            # Update SHA256
            sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha.outputs.sha }}\"|" ./asd.rb
            # Update version if present
            sed -i "s|version \".*\"|version \"${{ steps.latest_release.outputs.tag }}\"|" ./asd.rb
          else
            echo "asd.rb not found"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update to ${{ steps.latest_release.outputs.tag }}

            Auto-update Homebrew formula for app-state-diagram release ${{ steps.latest_release.outputs.tag }}
            
            - Updated download URL
            - Updated SHA256 hash: ${{ steps.sha.outputs.sha }}
            
            🤖 Generated by automated workflow"
            git push origin 1.x
            echo "Successfully updated Homebrew formula to ${{ steps.latest_release.outputs.tag }}"
          fi