name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: latest_release
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            # For workflow_dispatch, get latest release from API
            TAG=$(curl -s https://api.github.com/repos/alps-asd/app-state-diagram/releases/latest | grep -o '"tag_name": "[^"]*' | cut -d'"' -f4)
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi

      - name: Download release phar
        run: |
          wget https://github.com/alps-asd/app-state-diagram/releases/download/${{ steps.latest_release.outputs.tag }}/asd.phar

      - name: Calculate SHA256
        id: sha
        run: |
          SHA=$(sha256sum asd.phar | awk '{ print $1 }')
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Get current formula file
        id: get_formula
        run: |
          CONTENT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/alps-asd/homebrew-asd/contents/asd.rb?ref=1.x)
          echo "$CONTENT" | jq -r .content | base64 -d > current_formula.rb
          SHA=$(echo "$CONTENT" | jq -r .sha)
          echo "current_sha=$SHA" >> $GITHUB_OUTPUT

      - name: Update formula file
        run: |
          # Update the formula file
          sed -i "s|url \".*\"|url \"https://github.com/alps-asd/app-state-diagram/releases/download/${{ steps.latest_release.outputs.tag }}/asd.phar\"|" current_formula.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha.outputs.sha }}\"|" current_formula.rb

      - name: Update formula via GitHub API
        run: |
          UPDATED_CONTENT=$(base64 -w 0 current_formula.rb)
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/alps-asd/homebrew-asd/contents/asd.rb \
            -d "{
              \"message\": \"Update to ${{ steps.latest_release.outputs.tag }}\n\nAuto-update for app-state-diagram release ${{ steps.latest_release.outputs.tag }}\n- Updated download URL\n- Updated SHA256 hash: ${{ steps.sha.outputs.sha }}\n\n🤖 Generated by automated workflow\",
              \"content\": \"$UPDATED_CONTENT\",
              \"sha\": \"${{ steps.get_formula.outputs.current_sha }}\",
              \"branch\": \"1.x\"
            }"